# Generated by Django 3.0.3 on 2020-02-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0003_auto_20200216_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='category',
            field=models.CharField(choices=[('J', 'Jump'), ('S', 'Spin'), ('M', 'Move')], default='M', max_length=1),
        ),
    ]
