# Generated by Django 3.0.3 on 2020-06-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0005_auto_20200307_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='changeFoot',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='initialLeftForC',
            field=models.BooleanField(null=True),
        ),
    ]
