# Generated by Django 3.0.3 on 2020-06-17 02:29

from django.db import migrations

def simplifyEdges(apps, schema_editor):
    Transition = apps.get_model('sequences', 'Transition')
    Edge = apps.get_model('sequences', 'Edge')

    for transition in Transition.objects.all():
        newEntry = Edge.objects.filter(abbreviation=transition.entry.abbreviation[1:3]).first()
        transition.entry = newEntry
        newExit = Edge.objects.filter(abbreviation=transition.exit.abbreviation[1:3]).first()
        transition.exit = newExit
        transition.save()

class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0007_auto_20200617_0139'),
    ]

    operations = [
        migrations.RunPython(simplifyEdges, migrations.RunPython.noop)
    ]
