# Generated by Django 3.0.3 on 2020-07-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0009_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='ratingsAverage',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
        ),
    ]
