# Generated by Django 3.0.3 on 2020-07-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0011_sequence_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
