# Generated by Django 3.0.3 on 2020-07-06 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0012_auto_20200703_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transition',
            name='rotationDirection',
        ),
    ]
