# Generated by Django 3.0.3 on 2020-07-07 04:01

from django.db import migrations
from sequences.generator import Generator

def populateFrequencies(apps, schema_editor):
    Sequence = apps.get_model('sequences', 'Sequence')
    Move = apps.get_model('sequences', 'Move')

    for sequence in Sequence.objects.filter(name__isnull=False).iterator():
        transitions = Generator().transitionsWithFootFromSequence(sequence, True)
        for t in transitions:
            move = Move.objects.get(id=t.move.id)
            move.frequency += 1
            move.save()

def undoPopulateFrequencies(apps, schema_editor):
    Move = apps.get_model('sequences', 'Move')

    for move in Move.objects.all().iterator():
        move.frequency = 0
        move.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0014_move_frequency'),
    ]

    operations = [
        migrations.RunPython(populateFrequencies, undoPopulateFrequencies)
    ]
