# Generated by Django 3.0.3 on 2020-07-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0015_populate_frequencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='frequency_adult_bronze_nonstep',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='move',
            name='frequency_adult_bronze_step',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='move',
            name='frequency_adult_gold_nonstep',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='move',
            name='frequency_adult_gold_step',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='move',
            name='frequency_adult_silver_nonstep',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='move',
            name='frequency_adult_silver_step',
            field=models.IntegerField(default=0),
        ),
    ]
